name: Bootloader Build
on: push

jobs:
  run-build:
    name: Run Build
    runs-on: ubuntu-latest
    container:
      image: sicris/ccs-c2000-ubuntu:latest
      volumes:
        - ${{github.workspace}}:/myBuild
    steps:
      - name: Update
        run: apt update
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          ref: 'main'
          submodules: 'true'
      - name: List checkout files
        run: ls /myBuild
      - name: Build
        run: cd /myBuild && ./build.sh
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: /myBuild/artifact/
