name: Bootloader Build
on: push

jobs:
  run-build:
    name: Run Build
    runs-on: ubuntu-latest
    container:
      image: sicris/ccs-c2000-ubuntu:latest
      volumes:
        - ${{github.workspace}}:/myBuild
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Test (List checkout files)
        run: ls /myBuild
