name: Bootloader Build
on: push

jobs:
  run-build:
    name: Run Build
    runs-on: ubuntu-latest
    container:
      image: sicris/ccs-c2000-ubuntu:latest
      volumes:
        - ${{github.workspace}}:/myBuild
    steps:
      - name: TI tools
        run: ls -la /opt/ti
      - name: Test folders
        run: ls -la /
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          ref: 'main'
          submodules: 'true'
      - name: Test (List checkout files)
        run: ls /myBuild
